apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-forge.fullname" . }}
  labels:
    {{- include "data-forge.labels" . | nindent 4 }}
data:
  DATAFORGE_BROKER_REDIS_URL: {{ default (printf "redis://%s:%v/0" (include "data-forge.redisHost" .) .Values.redis.service.port) .Values.dataforge.brokerRedisUrl | quote }}
  DATAFORGE_REDIS_URL: {{ default (printf "redis://%s:%v/1" (include "data-forge.redisHost" .) .Values.redis.service.port) .Values.dataforge.redisUrl | quote }}
  DATAFORGE_OUTPUT_MODE: {{ .Values.dataforge.outputMode | quote }}
  DATAFORGE_CORS_ALLOWED_ORIGINS: {{ .Values.dataforge.corsAllowedOrigins | quote }}
  DATAFORGE_LOCAL_OUTPUT_PATH: {{ .Values.dataforge.localOutputPath | quote }}
  DATAFORGE_S3_OUTPUT_PATH: {{ .Values.dataforge.s3OutputPath | quote }}
  DATAFORGE_LOCAL_INPUT_MAPPINGS: {{ toJson .Values.dataforge.localInputMappings | quote }}
  DATAFORGE_DASK_N_WORKERS: {{ default "" .Values.dataforge.dask.nWorkers | quote }}
  DATAFORGE_DASK_THREADS_PER_WORKER: {{ .Values.dataforge.dask.threadsPerWorker | quote }}
  DATAFORGE_DASK_MEMORY_LIMIT: {{ .Values.dataforge.dask.memoryLimit | quote }}
  DATAFORGE_DASK_LOCAL_DIRECTORY: {{ default "" .Values.dataforge.dask.localDirectory | quote }}
  DATAFORGE_DASK_PROCESSES: {{ .Values.dataforge.dask.processes | quote }}
  DATAFORGE_DASK_PARALLEL_THRESHOLD: {{ .Values.dataforge.dask.parallelThreshold | quote }}
  {{- with .Values.dataforge.s3EndpointUrl }}
  DATAFORGE_S3_ENDPOINT_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.dataforge.stacApi }}
  DATAFORGE_STAC_API: {{ . | quote }}
  {{- end }}
  {{- with .Values.dataforge.stacTransactionApi }}
  DATAFORGE_STAC_TRANSACTION_API: {{ . | quote }}
  {{- end }}
  {{- with .Values.dataforge.stacDatanode }}
  DATAFORGE_STAC_DATANODE: {{ . | quote }}
  {{- end }}
  {{- with .Values.dataforge.stacConfigJson }}
  DATAFORGE_STAC_CONFIG_JSON: {{ . | quote }}
  {{- end }}
  {{- with .Values.dataforge.stacHrefMappings }}
  DATAFORGE_STAC_HREF_MAPPINGS: {{ . | quote }}
  {{- end }}
