{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-forge.redisHost" . }}
  labels:
    {{- include "data-forge.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "data-forge.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
{{- end }}
