{{- if .Values.secrets.create }}
{{- $apiKeys := .Values.secrets.apiKeys | default (list) }}
{{- $awsAccessKeyId := default "" .Values.secrets.awsAccessKeyId }}
{{- $awsSecretAccessKey := default "" .Values.secrets.awsSecretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-forge.fullname" . }}-secrets
  labels:
    {{- include "data-forge.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if gt (len $apiKeys) 0 }}
  DATAFORGE_API_KEYS: {{ join "," $apiKeys | quote }}
  {{- end }}
  {{- with $awsAccessKeyId }}
  AWS_ACCESS_KEY_ID: {{ . | quote }}
  {{- end }}
  {{- with $awsSecretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ . | quote }}
  {{- end }}
{{- end }}
