image:
  repository: ghcr.io/esgf2-us/data-forge
  tag: pr-4
  pullPolicy: IfNotPresent

api:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8000
  resources: {}
  podAnnotations: {}
  extraEnv: []

worker:
  replicaCount: 1
  resources: {}
  podAnnotations: {}
  extraEnv: []
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

redis:
  enabled: true
  image:
    repository: redis
    tag: 7-alpine
    pullPolicy: IfNotPresent
  service:
    port: 6379
  persistence:
    enabled: false
    size: 1Gi
  resources: {}

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: data-forge.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

dataforge:
  outputMode: local
  corsAllowedOrigins: "*"
  localOutputPath:
  s3OutputPath: s3://dataforge-kerchunks/kerchunks
  localInputMappings:
    - host_prefix: /home/titters/devel/work/data-forge/data/samples
      container_prefix: /datasets
  extraVolumeMounts:
    - name: datasets
      mountPath: /datasets
  dask:
    nWorkers:
    threadsPerWorker: "1"
    memoryLimit: 2GiB
    localDirectory:
    processes: "true"
    parallelThreshold: "4"

storage:
  mountPath: /data
  size: 20Gi

extraVolumes:
  - name: datasets
    hostPath:
      path: /home/titters/devel/work/data-forge/data/samples/

secrets:
  create: true

serviceAccount:
  create: false

podSecurityContext:
  fsGroup: 1000

containerSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
